# Generated by Django 3.0.2 on 2021-05-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('psw', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя контакта')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fullstack.Client', verbose_name='Имя клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('fromClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fullstack.Client', verbose_name='Имя клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('count', models.CharField(max_length=255, verbose_name='Количество')),
                ('fromProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fullstack.Products', verbose_name='Имя клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fullstack.Contacts_name', verbose_name='Имя контакта')),
            ],
        ),
    ]
