# Generated by Django 3.0.2 on 2021-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя контакта')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя контакта')),
                ('phone', models.CharField(max_length=255, verbose_name='Цена')),
            ],
        ),
    ]
