# Generated by Django 3.0.2 on 2021-03-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210319_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts_name',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.Client', verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='contacts_phone',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.Contacts_name', verbose_name='Имя контакта'),
        ),
    ]
